// Record history preview modal rendering.
async function openRecordPreview(id) {
  const record = await db.sheets.get(id);
  if (!record) return alert('Record not found.');
  const safe = escapeHtml;
  const thumbnails = await Promise.all(getRecordShotThumbnails(record).map(blobToBase64));
  const valueField = (label, value, wide = false) => `<div class="${wide ? 'md:col-span-2' : ''}"><label class="form-label">${safe(label)}</label><div class="preview-value form-input break-words bg-slate-950/70">${safe(value || '-')}</div></div>`;
  const cameras = (record.cameras || []).length ? `<div class="w-full overflow-x-auto rounded-lg border border-slate-800 bg-slate-950"><table class="w-full min-w-full table-fixed border-collapse text-left text-[10px]"><colgroup><col class="w-[5%]"><col class="w-[16%]"><col class="w-[16%]"><col span="11"></colgroup><thead class="bg-slate-900 text-slate-400"><tr><th class="px-2 py-1.5">Reel</th><th class="px-2 py-1.5">Camera</th><th class="px-2 py-1.5">Lens</th><th class="px-2 py-1.5">Focal</th><th class="px-2 py-1.5">Aperture</th><th class="px-2 py-1.5">Clip</th><th class="px-2 py-1.5">LUT</th><th class="px-2 py-1.5">Move.</th><th class="px-2 py-1.5">Height</th><th class="px-2 py-1.5">Distance</th><th class="px-2 py-1.5">Tilt</th><th class="px-2 py-1.5">Chart</th><th class="px-2 py-1.5">Plate</th><th class="px-2 py-1.5">Ref.</th></tr></thead><tbody class="divide-y divide-slate-800">${record.cameras.map(camera => `<tr class="text-slate-200"><td class="truncate px-2 py-1 font-bold text-amber-300">${safe(getCameraReelName(camera))}</td><td class="break-words px-2 py-1">${safe(camera.camera || '-')}</td><td class="break-words px-2 py-1">${safe(camera.lens || '-')}</td><td class="truncate px-2 py-1">${safe(camera.focal_length || '-')}</td><td class="truncate px-2 py-1">${safe(camera.t_stop || '-')}</td><td class="truncate px-2 py-1">${safe(camera.clip_name || '-')}</td><td class="truncate px-2 py-1">${safe(camera.lut_info || '-')}</td><td class="truncate px-2 py-1">${safe(camera.cramerawork || '-')}</td><td class="truncate px-2 py-1">${safe(camera.height_value || '-')}</td><td class="truncate px-2 py-1">${safe(camera.distance_value || '-')}</td><td class="truncate px-2 py-1">${safe(camera.tilt_value || '-')}</td><td class="truncate px-2 py-1">${safe(camera.flag_chart || 'NO')}</td><td class="truncate px-2 py-1">${safe(camera.flag_cleanplate || 'NO')}</td><td class="truncate px-2 py-1">${safe(camera.flag_reference || 'NO')}</td></tr>`).join('')}</tbody></table></div>` : '<p class="text-xs text-slate-500">No camera data.</p>';
  const canvasImage = record.images?.[0] ? await blobToBase64(record.images[0]) : '';
  const hdri = record.hdri_captured === 'YES' || record.hdri_captured === true;
  document.getElementById('recordPreviewModalTitle').textContent = `VFX Sheet #${record.id} | ${record.show_title || '-'} ${[record.episode, record.scene, record.shot].filter(Boolean).join('_') || '-'} | ${record.location || '-'}`;
  document.getElementById('recordPreviewModalMeta').innerHTML = `<table class="border-collapse"><tbody><tr><th class="pr-1 text-left font-medium text-slate-500">Operator</th><td class="pr-3 text-slate-300">${safe(record.operator || '-')}</td><th class="pr-1 text-left font-medium text-slate-500">Date & Time</th><td class="pr-3 text-slate-300">${safe(record.shoot_datetime || '-')}</td><th class="pr-1 text-left font-medium text-slate-500">GPS</th><td class="text-slate-300">${safe(record.gps_location || '-')}</td></tr></tbody></table>`;
  document.getElementById('recordPreviewModalContent').innerHTML = `<div class="space-y-3"><section class="space-y-2"><h2 class="text-[11px] font-semibold text-amber-400/80 uppercase tracking-wider">Multi-Camera Setup</h2><div class="w-full">${cameras}</div></section><hr class="border-slate-800"><section class="space-y-2"><h2 class="text-[11px] font-semibold text-amber-400/80 uppercase tracking-wider">HDRI Setup</h2><div class="grid grid-cols-3 gap-2">${valueField('HDRI Captured', hdri ? 'YES' : 'NO')}${valueField('Weather Conditions', Array.isArray(record.hdri_weather) ? record.hdri_weather.join(' / ') : record.hdri_weather)}${valueField('HDRI Notes / EV Range', record.hdri_notes)}</div></section><hr class="border-slate-800"><section class="space-y-2"><h2 class="text-[11px] font-semibold text-amber-400/80 uppercase tracking-wider">VFX Field Notes & Sketch</h2>${valueField('Notes', record.notes, true)}${thumbnails.length ? `<div><label class="form-label">Shot Data Thumbnail</label><div class="flex gap-2 overflow-x-auto">${thumbnails.map((url, index) => `<img src="${url}" alt="Shot thumbnail ${index + 1}" data-action="open-media-lightbox" class="h-20 min-w-28 cursor-zoom-in rounded-lg border border-slate-800 object-cover">`).join('')}</div></div>` : ''}${canvasImage ? `<div><label class="form-label">Sketch</label><img src="${canvasImage}" alt="VFX field sketch" data-action="open-media-lightbox" class="max-h-64 w-full cursor-zoom-in rounded-lg border border-slate-800 object-contain bg-slate-950"></div>` : ''}</section></div>`;
  document.getElementById('recordPreviewModal').classList.remove('hidden');
  document.body.classList.add('overflow-hidden');
}
